name: Testing
on:
  push:
    branches: ["*"]
    tags-ignore: ["*"]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:

  lint:
    name: Style & format checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install '.[dev]'
          python -m pip install -e .
      - name: Lint check
        run: |
          flake8 jsonscribe tests
      - name: Check format
        run: |
          yapf -dr jsonscribe tests

  test:
    name: Tests across multiple versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Install python ${{matrix.python-version}}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install '.[dev]'
          python -m pip install -e .
      - name: Run tests
        run: |
          coverage run -m unittest
          coverage report
          coverage xml -o ./coverage.xml
#      - name: Upload coverage report
#        uses: codecov/codecov-action@v1.5.0
#        with:
#          token: ${{secrets.CODECOV_TOKEN}}
#          file: ./coverage.xml
#          flags: unittests
#          fail_ci_if_error: true
